package com.mirjanakopanja.movieapp.files

import com.mirjanakopanja.movieapp.BuildConfig

const val DETAILS_INTENT_FILTER = "DETAILS INTENT FILTER"
const val DETAILS_LOAD_RESULT_EXTRA = "LOAD RESULT"
const val DETAILS_INTENT_EMPTY_EXTRA = "INTENT IS EMPTY"
const val DETAILS_DATA_EMPTY_EXTRA = "DATA IS EMPTY"
const val DETAILS_RESPONSE_EMPTY_EXTRA = "RESPONSE IS EMPTY"
const val DETAILS_REQUEST_ERROR_EXTRA = "REQUEST ERROR"
const val DETAILS_REQUEST_ERROR_MESSAGE_EXTRA = "REQUEST ERROR MESSAGE"
const val DETAILS_URL_MALFORMED_EXTRA = "URL MALFORMED"
const val DETAILS_RESPONSE_SUCCESS_EXTRA = "RESPONSE SUCCESS"
const val ID_EXTRA = "ID"
const val TITLE_EXTRA = "TITLE"
const val OVERVIEW_EXTRA = "OVERVIEW"
const val RATING_EXTRA = "RATING"
const val TAGLINE_EXTRA = "TAGLINE"
const val RELEASE_DATE_EXTRA = "RELEASE DATE"
const val SYSTEM_MESSAGE = "SYSTEM MESSAGE"
const val BASE_URL_IMG : String = "https://image.tmdb.org/t/p/original"

